config/routes.rb
Rails.application.routes.draw do

  
  get 'sessions/new'
  get 'users/new'
  post '/signup',  to: 'users#create'
  resources :users
  resources :events
  root 'events#index'
  get  '/signup',  to: 'users#new'
  get    '/login',   to: 'sessions#new'
  get    '/listEvent',   to: 'events#index'
  post   '/login',   to: 'sessions#create'
  delete '/logout',  to: 'sessions#destroy'
  post '/newevent',  to: 'events#create'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/event.rb
class Event < ApplicationRecord
end

app/models/user.rb
class User < ApplicationRecord
  has_many :events
  before_save { email.downcase! }
  validates :name, presence: true, length: { maximum: 50 }
  VALID_EMAIL_REGEX = /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i
  validates :email, presence: true, length: { maximum: 255 },
            format: { with: VALID_EMAIL_REGEX },
            uniqueness: { case_sensitive: false }

  has_secure_password
  validates :password, presence: true, length: { minimum: 6 }

  # Returns the hash digest of the given string.
  def User.digest(string)
    cost = ActiveModel::SecurePassword.min_cost ? BCrypt::Engine::MIN_COST :
               BCrypt::Engine.cost
    BCrypt::Password.create(string, cost: cost)
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
  include SessionsHelper
end

app/controllers/events_controller.rb
class EventsController < ApplicationController
  # before_action :logged_in_user, only: [:index]
   before_action :logged_in_user, only: [:edit, :update, :destroy]

  def edit
    @event = Event.find(params[:id])
  end

  def index
    if logged_in?
      @events = current_user.events
    else
      redirect_to login_url
    end
  end

  def new
    @event = Event.new
  end

  def show
    @events = Event.all
  end

  def create
    @event = Event.new(event_params)
    if @event.save
      flash[:success] = "Evento Creado Exitosamente!"
      redirect_to listEvent_url
    else
      render 'new'
    end
  end

  def logged_in_user
    unless logged_in?
      flash[:danger] = "Please log in."
      redirect_to login_url
    end
  end

  def update
    @event = Event.find(params[:id])
    if @event.update_attributes(event_params)
      redirect_to listEvent_url
    else
      render 'edit'
    end
  end

  def destroy
    Event.find(params[:id]).destroy
    # flash[:success] = "Eventos eliminados"
    redirect_to listEvent_url
  end

  def event_params
    params[:user_id] = current_user.id
    params.require(:event).permit(:name, :place, :organizer,
                                 :description, :user_id)
  end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def new
  end

  def create
    user = User.find_by(email: params[:session][:email].downcase)
    if user && user.authenticate(params[:session][:password])
      log_in user
      redirect_to listEvent_url
    else
      flash.now[:danger] = 'No coincide usuario y contraseña'
      render 'new'
    end
  end

  def destroy
    log_out
    redirect_to root_url
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def show
    @user = User.find(params[:id])
  end


  def index
    @users = User.all
  end

  def create
    @user = User.new(user_params)
    if @user.save
      log_in @user
      flash[:success] = "Bienvenido a EventGo"
      redirect_to listEvent_url
    else
      render 'new'
    end
  end

  def new
    @user = User.new
  end

  def user_params
    params.require(:user).permit(:name, :email, :password,
                                 :password_confirmation)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/events_helper.rb
module EventsHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
  # Logs in the given user.
  def log_in(user)
    session[:user_id] = user.id
  end

  # Returns the current logged-in user (if any).
  def current_user
    if (user_id = session[:user_id])
      @current_user ||= User.find_by(id: user_id)
    elsif (user_id = cookies.signed[:user_id])
      user = User.find_by(id: user_id)
      if user && user.authenticated?(cookies[:remember_token])
        log_in user
        @current_user = user
      end
    end
  end
  # Returns true if the user is logged in, false otherwise.
  def logged_in?
    !current_user.nil?
  end

  # Logs out the current user.
  def log_out
    session.delete(:user_id)
    @current_user = nil
  end
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/events/edit.html.erb
<% provide(:title, "Edit user") %>
<h1>Update your profile</h1>

<div class="row">
  <div class="col-md-6 col-md-offset-3">
    <%= form_for(@event) do |f| %>

      <%= f.label :name, "Nombre" %>
      <%= f.text_field :name %>

      <%= f.label :place, "Ubicación" %>
      <%= f.text_field :place %>

      <%= f.label :organizer,"Organizador" %>
      <%= f.text_field :organizer %>

      <%= f.label :description,"Descripción" %>
      <%= f.text_field :description %>

      <%= f.submit "Save changes", class: "btn btn-primary" %>
    <% end %>
  </div>
</div>

app/views/events/index.html.erb
<% provide(:title, 'Eventos') %>
<h1>Tus Eventos</h1>
<%= link_to "Crear",new_event_path %>
<table class=" table table-striped sortable">
  <thead>
  <tr>
    <th>Name</th>
    <th>Lugar</th>
    <th>Acciones</th>
  </tr>
  </thead>
  <tbody>
  <% @events.each do |event| %>
    <tr>
      <td> <%= link_to event.name %></td>
      <td><%= event.place %></td>
      <td> <%= link_to "Eliminar", event, method: :delete, data: { confirm: "You sure?" } %>
        <%= link_to "Editar",edit_event_path(event)%></td>    </tr>
  <% end %>
  </tbody>
</table>

app/views/events/new.html.erb
<% provide(:title, 'Sign up') %>
<h1>Sign up</h1>
<div class="row">
  <div class="col-md-6 col-md-offset-3">
    <%= form_for(@event, url: newevent_path) do |f| %>

      <%= f.label :name, "Nombre" %>
      <%= f.text_field :name %>

      <%= f.label :place, "Ubicación" %>
      <%= f.text_field :place %>

      <%= f.label :organizer,"Organizador" %>
      <%= f.text_field :organizer %>

      <%= f.label :description,"Descripción" %>
      <%= f.text_field :description %>

      <%= f.submit "Crear un evento", class: "btn btn-primary" %>
    <% end %>
  </div>
</div>

app/views/events/show.html.erb
<% provide(:title, 'Eventos') %>
<h1>All users</h1>
<table class=" table table-striped sortable">
  <thead>
  <tr>
    <th>Name</th>
    <th>Lugar</th>
    <th>Acciones</th>
  </tr>
  </thead>
  <tbody>
  <% @events.each do |event| %>
    <tr>
      <td> <%= link_to event.name %></td>
      <td><%= event.place %></td>
      <td> <%= link_to "Eliminar", event, method: :delete, data: { confirm: "You sure?" } %>
        <%= link_to "Editar",edit_event_path(event)%></td>    </tr>
  <% end %>
  </tbody>
</table>

app/views/layouts/_footer.html.erb
<footer class="footer">
  <small>
    Desarrollo de Soluciones Cloud
  </small>
  <nav>
    <ul>
<!--      <li><%#= link_to "About",   about_path %></li>-->
<!--      <li><%#= link_to "Contact", contact_path %></li>-->
      <li>Desarrollo de Soluciones Cloud</li>
    </ul>
  </nav>
</footer>

app/views/layouts/_header.html.erb
<header class="navbar navbar-fixed-top navbar-inverse">
  <div class="container">
    <%= link_to "EventGo", root_path, id: "logo" %>
    <nav>
      <ul class="nav navbar-nav navbar-right">
        <li><%= link_to "Home", root_path %></li>
<!--        <li><%#= link_to "Help", help_path %></li>-->
        <% if logged_in? %>
<!--          <li><%#= link_to "Users", '#' %></li>-->
          <li class="dropdown">
            <a href="#" class="dropdown-toggle" data-toggle="dropdown">
              Tú <b class="caret"></b>
            </a>
            <ul class="dropdown-menu">
              <li><%= link_to "Perfil", current_user %></li>
              <li><%= link_to "Configuración", '#' %></li>
              <li class="divider"></li>
              <li>
                <%= link_to "Salir", logout_path, method: :delete %>
              </li>
            </ul>
          </li>
        <% else %>
          <li><%= link_to "Ingresar", login_path %></li>
        <% end %>
      </ul>
    </nav>
  </div>
</header>

app/views/layouts/_shim.html.erb
<!--[if lt IE 9]>
<script src="//cdnjs.cloudflare.com/ajax/libs/html5shiv/r29/html5.min.js">
</script>
<![endif]-->

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>EventGo</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
    <%= render 'layouts/shim' %>
  </head>

  <body>
  <%= render 'layouts/header' %>
  <div class="container">
    <% flash.each do |message_type, message| %>
      <div class="alert alert-<%= message_type %>"><%= message %></div>
    <% end %>
    <%= yield %>
    <%= render 'layouts/footer' %>
  </div>
  </body>
</html>

app/views/shared/_error_messages.html.erb
<% if @user.errors.any? %>
  <div id="error_explanation">
    <div class="alert alert-danger">
      El formulario contuene <%= pluralize(@user.errors.count, "errores") %>.
    </div>
    <ul>
      <% @user.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
    </ul>
  </div>
<% end %>

app/views/users/new.html.erb
<% provide(:title, 'Registrate') %>
<h1>Registrate</h1>
<div class="row">
  <div class="col-md-6 col-md-offset-3">
    <%= form_for(@user, url: signup_path) do |f| %>
      <%= render 'shared/error_messages' %>

      <%= f.label :name," Nombre y apellido" %>
      <%= f.text_field :name, class: 'form-control' %>

      <%= f.label :email, "Correo electrónico" %>
      <%= f.email_field :email, class: 'form-control' %>

      <%= f.label :password, "Contraseña" %>
      <%= f.password_field :password, class: 'form-control' %>

      <%= f.label :password_confirmation, "Confirma contraseña" %>
      <%= f.password_field :password_confirmation, class: 'form-control' %>

      <%= f.submit "Crear cuenta", class: "btn btn-primary" %>
    <% end %>
  </div>
</div>

app/views/users/show.html.erb
<% provide(:title, @user.name) %>
<div class="row">
  <aside class="col-md-4">
    <section class="user_info">
      <h1>
        <%#= gravatar_for @user %>
        <%= @user.name %>
      </h1>
    </section>
  </aside>
</div>